// Code generated by aru model:build from model.go. DO NOT EDIT.

package attempt

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Attempts starts a query on the table of Attempt, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Attempts(db model.DB) *AttemptQuery { return &AttemptQuery{b: attemptTable.Query(db)} }

// AttemptQuery is a query on the table of Attempt.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Attempt rows or a value; there is
// no way to run one without a Grant.
type AttemptQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *AttemptQuery) Base() *model.Builder { return q.b }

// New returns an empty Attempt on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *AttemptQuery) New() (*Attempt, error) {
	e, err := q.b.NewModelInstance(nil)
	return attemptOf(e), err
}

// AttemptCollection is rows of Attempt, as a query returns them.
type AttemptCollection []*Attempt

// AttemptCollectionOf converts rows of the table of Attempt. A nil input is a nil
// collection.
func AttemptCollectionOf(rows model.Rows) AttemptCollection {
	if rows == nil {
		return nil
	}
	out := make(AttemptCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Attempt)
	}
	return out
}

func attemptOf(e model.Entity) *Attempt {
	row, _ := e.(*Attempt)
	return row
}

// attemptColumn turns a closure over AttemptQuery into one over the core builder, so
// passing func(*AttemptQuery) where a column goes adds a parenthesised group.
func attemptColumn(column any) any {
	if group, ok := column.(func(*AttemptQuery)); ok {
		return func(b *model.Builder) { group(&AttemptQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *AttemptQuery) Clone() *AttemptQuery { return &AttemptQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*AttemptQuery) in place of the column adds a group.
func (q *AttemptQuery) Where(column any, args ...any) *AttemptQuery {
	q.b.Where(attemptColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*AttemptQuery) in place of the column adds a group.
func (q *AttemptQuery) OrWhere(column any, args ...any) *AttemptQuery {
	q.b.OrWhere(attemptColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *AttemptQuery) WhereNot(column any, args ...any) *AttemptQuery {
	q.b.WhereNot(attemptColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *AttemptQuery) OrWhereNot(column any, args ...any) *AttemptQuery {
	q.b.OrWhereNot(attemptColumn(column), args...)
	return q
}

func (q *AttemptQuery) WhereIn(column any, values []any) *AttemptQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *AttemptQuery) WhereNotIn(column any, values []any) *AttemptQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *AttemptQuery) WhereNull(columns ...any) *AttemptQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *AttemptQuery) WhereNotNull(columns ...any) *AttemptQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *AttemptQuery) WhereBetween(column any, from, to any) *AttemptQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *AttemptQuery) WhereColumn(first any, args ...any) *AttemptQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *AttemptQuery) WhereKey(id any) *AttemptQuery {
	q.b.WhereKey(id)
	return q
}

func (q *AttemptQuery) WhereExists(callback func(*query.Builder)) *AttemptQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *AttemptQuery) WhereNotExists(callback func(*query.Builder)) *AttemptQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *AttemptQuery) WhereHas(relation string, callback func(*query.Builder)) *AttemptQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *AttemptQuery) OrWhereHas(relation string, callback func(*query.Builder)) *AttemptQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *AttemptQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *AttemptQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *AttemptQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *AttemptQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *AttemptQuery) WhereRelation(relation string, column any, args ...any) *AttemptQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *AttemptQuery) OrWhereRelation(relation string, column any, args ...any) *AttemptQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *AttemptQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *AttemptQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *AttemptQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *AttemptQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *AttemptQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *AttemptQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *AttemptQuery) OrHas(relation, operator string, count int) *AttemptQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *AttemptQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *AttemptQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *AttemptQuery) OrDoesntHave(relation string) *AttemptQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *AttemptQuery) Select(columns ...any) *AttemptQuery {
	q.b.Select(columns...)
	return q
}

func (q *AttemptQuery) AddSelect(columns ...any) *AttemptQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *AttemptQuery) SelectRaw(expression string, bindings ...any) *AttemptQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *AttemptQuery) Join(table any, first any, args ...any) *AttemptQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *AttemptQuery) GroupBy(groups ...any) *AttemptQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *AttemptQuery) OrderBy(column any, direction ...string) *AttemptQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *AttemptQuery) OrderByDesc(column any) *AttemptQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *AttemptQuery) Latest(column ...string) *AttemptQuery {
	q.b.Latest(column...)
	return q
}

func (q *AttemptQuery) Oldest(column ...string) *AttemptQuery {
	q.b.Oldest(column...)
	return q
}

func (q *AttemptQuery) Limit(value int) *AttemptQuery {
	q.b.Limit(value)
	return q
}

func (q *AttemptQuery) Offset(value int) *AttemptQuery {
	q.b.Offset(value)
	return q
}

func (q *AttemptQuery) ForPage(page, perPage int) *AttemptQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *AttemptQuery) With(relations ...string) *AttemptQuery {
	q.b.With(relations...)
	return q
}

func (q *AttemptQuery) WithCount(relations ...string) *AttemptQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *AttemptQuery) WithExists(relation string) *AttemptQuery {
	q.b.WithExists(relation)
	return q
}

func (q *AttemptQuery) WithSum(relation, column string) *AttemptQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *AttemptQuery) WithAvg(relation, column string) *AttemptQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *AttemptQuery) WithMin(relation, column string) *AttemptQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *AttemptQuery) WithMax(relation, column string) *AttemptQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *AttemptQuery) Without(relations ...string) *AttemptQuery {
	q.b.Without(relations...)
	return q
}

func (q *AttemptQuery) WithoutGlobalScope(identifier string) *AttemptQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *AttemptQuery) WithoutGlobalScopes(identifiers ...string) *AttemptQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *AttemptQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (AttemptCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return AttemptCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *AttemptQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Attempt, error) {
	e, err := q.b.First(ctx, g, columns...)
	return attemptOf(e), err
}

func (q *AttemptQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Attempt, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return attemptOf(e), err
}

func (q *AttemptQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Attempt, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return attemptOf(e), err
}

func (q *AttemptQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Attempt, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return attemptOf(e), err
}

func (q *AttemptQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Attempt, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return attemptOf(e), err
}

func (q *AttemptQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Attempt, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return attemptOf(e), err
}

func (q *AttemptQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Attempt, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return attemptOf(e), err
}

func (q *AttemptQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Attempt, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return attemptOf(e), err
}

func (q *AttemptQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (AttemptCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return AttemptCollectionOf(rows), err
}

func (q *AttemptQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Attempt, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return attemptOf(e), err
}

func (q *AttemptQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Attempt, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return attemptOf(e), err
}

func (q *AttemptQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Attempt, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return attemptOf(e), err
}

func (q *AttemptQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Attempt, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return attemptOf(e), err
}

func (q *AttemptQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (AttemptCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return AttemptCollectionOf(rows), meta, err
}

func (q *AttemptQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (AttemptCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return AttemptCollectionOf(rows), meta, err
}

func (q *AttemptQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (AttemptCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return AttemptCollectionOf(rows), meta, err
}

func (q *AttemptQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(AttemptCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(AttemptCollectionOf(rows), page)
	})
}

func (q *AttemptQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Attempt, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(attemptOf(e), index)
	})
}

func (q *AttemptQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Attempt, error] {
	return func(yield func(*Attempt, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(attemptOf(e), err) {
				return
			}
		}
	}
}

func (q *AttemptQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *AttemptQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *AttemptQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *AttemptQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *AttemptQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *AttemptQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *AttemptQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *AttemptQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *AttemptQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *AttemptQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *AttemptQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *AttemptQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *AttemptQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *AttemptQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *AttemptQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *AttemptQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *AttemptQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *AttemptQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *AttemptQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c AttemptCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c AttemptCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c AttemptCollection) Find(key any) *Attempt { return attemptOf(c.Rows().Find(key)) }

func (c AttemptCollection) FindOrFail(key any) (*Attempt, error) {
	e, err := c.Rows().FindOrFail(key)
	return attemptOf(e), err
}

func (c AttemptCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c AttemptCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c AttemptCollection) Only(keys ...any) AttemptCollection {
	return AttemptCollectionOf(c.Rows().Only(keys...))
}

func (c AttemptCollection) Except(keys ...any) AttemptCollection {
	return AttemptCollectionOf(c.Rows().Except(keys...))
}

func (c AttemptCollection) Unique() AttemptCollection { return AttemptCollectionOf(c.Rows().Unique()) }

func (c AttemptCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c AttemptCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c AttemptCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c AttemptCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (AttemptCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return AttemptCollectionOf(rows), err
}

func (c AttemptCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Attempt; it shadows the untyped one the
// embedded model promotes.
func (row *Attempt) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Attempt, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return attemptOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Attempt) Replicate(except ...string) (*Attempt, error) {
	e, err := row.Model.Replicate(except...)
	return attemptOf(e), err
}
